# bot related constants
TOKEN = "MTIyMDQxOTY2OTM3OTM4MzM3Ng.Gz7ug4.AwIcTXV57TEwlfR2GPTKAOwJayghwiI2RCy3TE"

# Ollivanders shop related constants
creatures = ["Acromantula", "Basilisk", "Boggart", "Centaur", "Chimaera", "Cornish Pixie", "Demiguise", "Dementor", "Diricawl", "Doxy", "Dragon", "Dugbog", "Erumpent", "Fawkes", "Flobberworm", "Fwooper", "Ghoul", "Giant", "Goblin", "Graphorn", "Grindylow", "Hippogriff", "House-Elf", "Hungarian Horntail", "Imp", "Jarvey", "Jobberknoll",
             "Kappa", "Kelpie", "Knarl", "Kraken", "Merpeople", "Manticore", "Niffler", "Nogtail", "Occamy", "Phoenix", "Pixie", "Pogrebin", "Porlock", "Quintaped", "Ramora", "Re'em", "Runespoor", "Salamander", "Sea Serpent", "Snidget", "Sphinx", "Streeler", "Tebo", "Troll", "Unicorn", "Veela", "Werewolf", "Winged Horse", "Yeti", "Zouwu"]

wood = ["Acacia", "Alder", "Apple", "Ash", "Beech", "Blackthorn", "Cedar", "Cherry", "Chestnut", "Ebony",
        "Elder", "Elm", "Fir", "Hawthorn", "Hazel", "Holly", "Hornbeam", "Larch", "Laurel", "Maple", "Oak",
        "Pear", "Pine", "Poplar", "Redwood", "Rowan", "Spruce", "Sycamore", "Vine", "Walnut", "Willow", "Yew"]

core = ["Ashwinder Ash", "Augurey Feather", "Billywig Stinger", "Bicorn Horn", "Boomslang Skin", "Dragon Heartstring", "Phoenix Feather", "Unicorn Hair", "Basilisk Horn", "Kelpie Hair", "Thunderbird Tail Feather", "Veela Hair",
        "Wampus Cat Hair", "Horned Serpent Horn", "Rougarou Hair", "Snallygaster Heartstring", "Jackalope Antler", "Thunderbird Feather", "Rougarou Fang", "White River Monster Spine", "Swamp Mayhaw", "Horned Serpent Horn"]

length = ["9", "9 1/2", "10", "10 1/2", "11",
          "11 1/2", "12", "12 1/2", "13", "13 1/2", "14"]

terms = [
    "Hogwarts", "Witch", "Wizard", "Durmstrang", "Beauxbatons", "Castle",
    "Dungeon", "Nargle", 'Nargles', "Serpent", "Snake", "Eagle", "Lion",
    "Half Blood Prince", "Godric", "Salazar", "Rowena", "Helga",
    "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff",
    "Quidditch", "Golden Snitch", "Snitch", "Quaffle", "Bludger", "Beater", "Seeker", "Chaser", "Keeper",
    "Sorting Hat",
    "Marauder's Map", "Marauders", "Marauder",
    "Triwizard Tournament", "Triwizard Cup",
    "Deathly Hallows", "Deathly Hallow", "Elder Wand", "Resurrection Stone", "Invisibility Cloak",
    "Horcruxes",
    "Patronus",
    "Muggle", "Mudblood",
    "Order Of The Phoenix", "Order Of Phoenix", "Phoenix",
    "Ministry of Magic",
    "Diagon Alley", "Hogsmeade"
    "Platform 9¾", "Hogwarts Express",
    "Forbidden Forest",
    "Chamber of Secrets",
    "Philosopher's Stone",
    "Azkaban",
    "Whomping Willow",
    "Polyjuice Potion", "Draught Of Living Death", "Potion", "Felix Felicis", "Amortentia", "Wolfsbane",
    "Room of Requirement",
    "Parseltongue",
    "Mirror of Erised",
    "Goblet of Fire",
    "House-Elf", "Elf", "House Elf",
    "Thestral",
    "Floo Powder", "Floo",
    "Bezoar",
    "Occlumency", "Legilimency",
    "Gringotts",
    "Quibbler", "Daily Prophet",
    "St. Mungo's",
    "Spell", "Magic", "Ghosts", "Poltergeist",
    "Transfiguration", "Charms", "Defence Against The Dark Arts", "Herbology", "Divination", "Arithmancy", "Potions", "Astronomy", "History of Magic",
    "Spew", "Prefect", "Time Turner",
            "Wand", "Broom", "Cauldron",
            "Pensieve",
            "Portkey",
            "Howler",
            "Vanishing Cabinet",
            "Wizengamot",
            "Knuts", "Sickles", "Galleons",
            "Apparition", "Apparate",
            "Curse", "Jinx", "Hex",
            "Zonkos", "Three Broomsticks", "Hog's Head", "Ollivanders", "Shrieking Shack", "Leaky Cauldron",
            "Newts", "Owls", "Owl", "Newt",
            "Yule Ball",
            "Common Room",
            "Privet Drive", "Grimmauld Place", "Grimmauld",
            "Remembrall", "Sword", "Diadem"
            "Animagus", "Knight Bus"
]

characters = [
    "Harry Potter", "Harry", "Potter", "Lily", "Evans", "James", "Sirius", "Black", "Sirius Black", "Lupin", "Remus", "Remus Lupin",
    "Hermione Granger", "Hermione", "Granger",
    "Ron Weasley", "Ron", "Weasley", "Ginny", "Fred", "George", "Percy", "Molly", "Arthur", "Bill", "Charlie",
    "Albus Dumbledore", "Dumbledore", "Albus", "Aberforth",
    "Severus Snape", "Severus", "Snape",
    "Lord Voldemort", "Voldemort", "Tom Riddle", "Riddle", "Tom",
    "Rubeus Hagrid", "Hagrid",
    "Draco Malfoy", "Malfoy", "Draco", "Lucius", "Narcissa",
    "Neville Longbottom", "Neville", "Longbottom", "Augusta", "Alice", "Frank",
    "Luna Lovegood", "Luna", "Lovegood", "Xenophilius",
    "Bellatrix Lestrange", "Bellatrix", "Lestrange", "Rodulphus",
    "Nymphadora Tonks", "Teddy", "Ted", "Tonks", "Andromeda",
    "Cedric Diggory", "Cedric", "Diggory", "Amos",
    "Dobby", "Winky", "Kreacher",
    "Cho Chang", "Cho",
    "Fleur Delacour", "Fleur",
    "Viktor Krum", "Krum",
    "Dolores Umbridge", "Umbridge", "Dolores",
    "Gilderoy Lockhart", "Lockhart",
    "Minerva Mcgonagall", "Mcgonagall", "Minerva", "Marge",
    "Sybill Trelawney", "Trelawney",
    "Filius Flitwick", "Flitwick","Filius",
    "Pomona Sprout", "Sprout",
    "Argus Filch", "Filch", "Norris", "Mrs Norris",
    "Poppy Pomfrey", "Pomfrey",
    "Cornelius Fudge", "Fudge", "Cornelius",
    "Barty Crouch", "Crouch",
    "Dudley Dursley", "Petunia", "Vernon ", "Dursley",
    "Olympe Maxime", "Madame Maxime", "Maxime",
    "Madam Rosmerta", "Rosmerta",
    "Lavender Brown", "Lavender",
    "Parvati Patil", "Parvati", "Padma", "Padma Patil",
    "Dean Thomas", "Dean", "Seamus Finnigan", "Seamus",
    "Oliver Wood", "Wood", "Oliver", "Marcus Flint", "Flint", "Katie Bell", "Katie", "Angelina Johnson", "Angelina", "Alicia Spinnet", "Alicia",
    "Lee Jordan", "Lee",
    "Vincent Crabbe", "Crabbe", "Gregory Goyle", "Goyle", "Pansy Parkinson", "Pansy",
    "Peeves", "Nearly Headless Nick", "Bloody Baron", "Fat Friar", "Grey Lady", "Moaning Myrtle",
    "Arabella Figg", "Mrs Figg", "Figg",
    "Igor Karkaroff", "Karkaroff", "Igor",
    "Mad-Eye Moody", "Moody", "Alastor", "Alastor Moody",
    "Rita Skeeter", "Skeeter",
    "Stan Shunpike", "Ern", "Ernie",
    "Kingsley Shacklebolt", "Kingsley",
    "Gellert Grindelwald", "Grindelwald",
    "Bathilda Bagshot", "Bathilda",
    "Peter Pettigrew", "Wormtail", "Pettigrew", "Peter", "Moony", "Padfoot", "Prongs",
    "Marvolo Gaunt", "Merope Gaunt", "Morfin Gaunt", "Gaunt",
    "Grawp", "Firenze", "Griphook",
    "Fenrir Greyback", "Greyback",
    "Scorpius", "Rose", "Hugo",
    "Hedwig", "Scabbers", "Crookshanks", "Norbert", "Trevor", "Buckbeak", "Nagini", "Aragog", "Fluffy", "Fang",
    "Yaxley", "Zabini", "Blaise", "Blaise Zabini", "Zacharias", "Zacharias Smith",
    "Colin Creevey", "Colin", "Dennis", "Dennis Creevey", "Susan Bones", "Susan", "Nott"
]

spells = [
    "Accio",
    "Aguamenti",
    "Alohomora",
    "Anapneo",
    "Aparecium",
    "Avada Kedavra",
    "Avis",
    "Colloportus",
    "Crucio",
    "Diffindo",
    "Disillusionment Charm",
    "Dissendium",
    "Engorgio",
    "Episkey",
    "Evanesco",
    "Expecto Patronum",
    "Expelliarmus",
    "Expulso",
    "Ferula",
    "Fidelius Charm",
    "Finestra",
    "Flagrate",
    "Flipendo",
    "Furnunculus",
    "Geminio",
    "Glacius",
    "Homorphus Charm",
    "Immobulus",
    "Impedimenta",
    "Imperio",
    "Impervius",
    "Incarcerous",
    "Incendio",
    "Langlock",
    "Legilimens",
    "Levicorpus",
    "Liberacorpus",
    "Locomotor",
    "Lumos",
    "Lumos Maxima",
    "Lumos Solem",
    "Morsmordre",
    "Muffliato",
    "Nox",
    "Obliviate",
    "Obscuro",
    "Oppugno",
    "Pack",
    "Petrificus Totalus",
    "Point Me",
    "Portus",
    "Prior Incantato",
    "Protego",
    "Protego Horribilis",
    "Protego Totalum",
    "Quietus",
    "Reducto",
    "Relashio",
    "Rennervate",
    "Reparo",
    "Rictusempra",
    "Riddikulus",
    "Scourgify",
    "Sectumsempra",
    "Serpensortia",
    "Silencio",
    "Sonorus",
    "Specialis Revelio",
    "Stupefy",
    "Tarantallegra",
    "Tergeo",
    "Unbreakable Vow",
    "Vulnera Sanentur",
    "Wingardium Leviosa"
]
trivia = {
    "What is the name of the train station where the Hogwarts Express departs from?": ["King's Cross Station", "Kings Cross", "King's Cross"],
    "Who is the headmaster of Hogwarts when Harry Potter first attends?": ["Albus Dumbledore", "Dumbledore"],
    "What is the name of Hagrid's giant half-brother?": ["Grawp"],
    "Which book does the character Luna Lovegood first appear in?": ["Harry Potter And The Order Of The Phoenix", "Order Of The Phoenix", "Order Of Phoenix"],
    "What is the disarming spell?": ["Expelliarmus"],
    "Who is the ghost of Slytherin House?": ["The Bloody Baron", "Bloody Baron"],
    "What is the phrase to 'wipe' the Marauder's Map after use?": ["Mischief Managed"],
    "How many members are in a Quidditch team?": ["7"],
    "Who teaches Divination at Hogwarts?": ["Professor Sybill Trelawney", "Trelawney", "Sybill Trelawney"],
    "What type of snake does Harry set free from the zoo in the first book?": ["Boa Constrictor"],
    "What is the name of Luna Lovegood's father?": ["Xenophilius Lovegood", "Xenophilius"],
    "What does the acronym 'OWLs' stand for in the wizarding world?": ["Ordinary Wizarding Levels"],
    "What does the acronym 'NEWTs' stand for in the wizarding world?": ["Nastily Exhausting Wizarding Tests"],
    "What is the name of Hermione's cat?": ["Crookshanks"],
    "What type of creature is Buckbeak?": ["Hippogriff"],
    "What is the name of the town where Harry's parents lived and were killed by Voldemort?": ["Godric's Hollow", "Godrics Hollow"],
    "Who is the potions master at Hogwarts during Harry's sixth year?": ["Horace Slughorn", "Slughorn"],
    "What is the name of the goblin who helps Harry break into Gringotts Bank?": ["Griphook"],
    "Which dragon does Harry face in the Triwizard Tournament?": ["Hungarian Horntail"],
    "What is the name of the street where the Dursleys live?": ["Privet Drive"],
    "What is the spell used to create light at the tip of the caster's wand?": ["Lumos"],
    "What is the name of the house elf who serves the Black family?": ["Kreacher"],
    "Who is the caretaker at Hogwarts?": ["Argus Filch", "Filch"],
    "What is the name of the house elf who Crouch fired in the fourth book?": ["Winky"],
    "Who teaches Care of Magical Creatures at Hogwarts?": ["Rubeus Hagrid", "Hagrid"],
    "Which Weasley sibling is the oldest?": ["Bill Weasley", "Bill"],
    "What type of dragon does Hagrid raise in his hut during Harry's first year?": ["Norwegian Ridgeback"],
    "What is the name of the pub in Hogsmeade where Harry first learns about Sirius Black?": ["The Three Broomsticks", "Three Broomsticks"],
    "What is the name of the three headed dog in the first book?": ["Fluffy"],
    "What is the spell used to conjure a Patronus?": ["Expecto Patronum"],
    "What is the unlocking spell?": ["Alohomora"],
    "Who is the Ravenclaw house ghost?": ["The Grey Lady", "Helena Ravenclaw", "Grey Lady", "Helena"],
    "What is the name of Ron Weasley's pet rat?": ["Scabbers"],
    "What position does Harry play on the Gryffindor Quidditch team?": ["Seeker"],
    "Who is the Half-Blood Prince?": ["Severus Snape", "Snape"],
    "What is the name of the device used to travel back in time in the third book?": ["Time Turner"],
    "What is Voldemort's middle name?": ["Marvolo"],
    "Who is the head of the Department of Magical Law Enforcement in the Ministry of Magic?": ["Amelia Bones"],
    "What is the name of the potion that allows a drinker to transform into someone else?": ["Polyjuice Potion", "Polyjuice"],
    "What is the name of the wizarding prison guarded by Dementors?": ["Azkaban"],
    "What is the name of the werewolf who infects Remus Lupin?": ["Fenrir Greyback", "Greyback"],
    "What is the name of the group of dark wizards and witches who serve Lord Voldemort?": ["Death Eaters"],
    "Who is the author of 'Fantastic Beasts and Where to Find Them' in the wizarding world?": ["Newt Scamander"],
    "What is the name of Harry Potter's owl?": ["Hedwig"],
    "What is the name of Neville's toad?": ["Trevor"],
    "What is Hermione's middle name?": ["Jean"],
    "What is the phone number to enter the Ministry of Magic through the telephone booth in Muggle London?": ["62442"]
}

# for emojis game
d = {":zap: :owl: :broom: ": ["Harry", "Harry Potter"],
     ":books: :cat2: :100: ": ["Hermione", "Hermione Granger"],
     ":ear: :man_red_haired: :fireworks: ": ["George", "George Weasley"],
     ":spider_web: :crown: :chess_pawn:": ["Ron", "Ron Weasley"],
     ":skull: :man_bald: :snake: ": ["Tom Riddle", "Voldemort"],
     ":man_mage: :european_castle: :lemon: ": ["Dumbledore", "Albus Dumbledore"],
     ":closed_umbrella: :hut: :dog: ": ["Hagrid", "Rubeus Hagrid"],
     ":ribbon: :cat: :writing_hand: ": ["Umbridge", "Dolores Umbridge"],
     ":flag_fr: :blond_haired_woman: :sparkles: ": ["Fleur", "Fleur Delacour"],
     " :moneybag: :green_apple: :snake: ": ["Draco", "Draco Malfoy"], ":socks: :dagger: :chains: ": ["Dobby"],
     ":wolf: :full_moon: :chocolate_bar: ": ["Lupin", "Remus Lupin", "Remus", "Moony"],
     ":rat: :knife: :rightwards_hand: ": ["Peter", "Peter Pettigrew", "Pettigrew", "Wormtail"],
     ":eagle: :blond_haired_woman: :crescent_moon: ": [
    'Luna', 'Luna Lovegood'], ":ghost: :knife: :head_bandage: ": ['Sir Nicholas', 'Nearly Headless Nick'],
    ":crystal_ball: :coffee: :eyes: ": ["Trelawney", "Sybill Trelawney"],
    ":ghost: :toilet: :weary: ": ["Myrtle", "Moaning Myrtle"],
    ":badger: :trophy: :skull: ": ["Cedric", "Cedric Diggory"],
    ":woman_wearing_turban: :garlic: :skull: ": ["Quirrell", "Quirinus Quirrell"],
    ":woman_red_haired: :yarn: :fork_knife_plate: ": ["Molly", "Molly Weaasley"],
    ":frog: :potted_plant: :lion_face: ": ["Neville", "Neville Longbottom"],
    ":woman_red_haired: :broom: :lion_face: ": ["Ginny", "Ginny Weasley"],
    ":black_circle: :dog: :chains: ": ["Sirius", "Sirius Black"],
    ":woman_mage: :cat: :sparkles: ": ["Mcgonagall", "Minerva Mcgonagall"],
    ":deer: :eyeglasses: :lion_face: ": ["James", "James Potter"],
    ":duck: :oncoming_automobile: :telephone: ": ["Arthur", "Arthur Weasley"],
    ":flag_bg:  :stadium: :broom: ": ["Krum", "Victor Krum"]}

# corssword game
cross = {
    r'assets\images\cross1.png': {'1': 'Caldron', '2': 'Glasses', '3': 'Wand', '4': 'Owl', '5': 'Potion', '6': 'Sortinghat',
                                 '7': 'Cloak', '8': 'Goldensnitch', '9': 'Broomstick', '10': 'Scar', '11': 'Cupboard'},
    r'assets\images\cross2.png': {'1': 'Voldemort', '2': 'Dumbledore', '3': 'Ron', '4': 'Broom', '5': 'Draco',
                                 '6': 'Slytherin', '7': 'Hagrid', '8': 'Hedwig', '9': 'Scabbers', '10': 'Fluffy',
                                 '11': 'Dudley'},
    r'assets\images\cross3.png': {'1': 'Muggle', '2a': 'Hogwarts', '2d': 'Hogsmeade', '3': 'Sirius', '4': 'Scabbers',
                                 '5': 'Hedwig', '6': 'Honeydukes', '7': 'Alohomora', '8': 'Azkaban', '9': 'Always',
                                 '10a': 'Dumbledore', '10d': 'Dobby', '11': 'Quidditch', '12': 'Fluffy', '13': 'Voldemort'},
    r'assets\images\cross4.png': {'1': 'Hedwig', '2': 'Weasley', '3': 'Hermione', '4': 'Neville', '5': 'Scabbers',
                                 '6': 'Hagrid', '7': 'Dudley', '8': 'Draco', '9': 'Dumbledore'},
    r'assets\images\cross5.png': {'1': 'Hogwartsexpress', '2': 'Hufflepuff', '3': 'Ravenclaw', '4': 'Owls', '5': 'Boats',
                                 '6': 'Diagonalley', '7': 'Toads', '8': 'Slytherin', '9': 'Sortinghat', '10': 'Hogwarts'},
    r'assets\images\cross6.png': {'1': 'Expelliarmus', '2': 'Lumos', '3': 'Dumbledoresarmy', '4': 'Darkmark',
                                 '5': 'Goldensnitch', '6': 'Hufflepuff', '7': 'Hagrid', '8': 'Tomriddle', '9': 'Hogwarts',
                                 '10': 'Basilisk', '11': 'Hermionegranger', '12': 'Hedwig'},
    r'assets\images\cross7.png': {'1': 'Voldemort', '2': 'Theburrow', '3': 'Crookshanks', '4': 'Dobby', '5': 'Snape',
                                 '6': 'Privetdrive', '7': 'Diagon', '8': 'Scared', '9a': 'Every', '9d': 'Errol'},
    r'assets\images\cross8.png': {'1': 'Riddikulus', '2': 'Hedwig', '3': 'Hufflepuff', '4': 'Slytherin', '5': 'Ravenclaw',
                                 '6': 'Fluffy', '7': 'Trolls', '8': 'Muggle', '9': 'Opens', '10': 'Tea', '11': 'Die',
                                 '12': 'Hogwarts'},
    r'assets\images\cross9.png': {'1': 'Deluminator', '2': 'Howler', '3': 'Wand', '4': 'Invisibilitycloak', '5': 'Voldemort',
                                 '6': 'Rubeushagrid', '7': 'AvadaKedavra', '8': 'Gryffindor', '9': 'Hufflepuff',
                                 '10': 'Quidditch'}
}
