# bot related constants
TOKEN = "MTIyMDQxOTY2OTM3OTM4MzM3Ng.Gz7ug4.AwIcTXV57TEwlfR2GPTKAOwJayghwiI2RCy3TE"

# Ollivanders shop related constants
creatures = ["Acromantula", "Basilisk", "Boggart", "Centaur", "Chimaera", "Cornish Pixie", "Demiguise", "Dementor", "Diricawl", "Doxy", "Dragon", "Dugbog", "Erumpent", "Fawkes", "Flobberworm", "Fwooper", "Ghoul", "Giant", "Goblin", "Graphorn", "Grindylow", "Hippogriff", "House-Elf", "Hungarian Horntail", "Imp", "Jarvey", "Jobberknoll",
             "Kappa", "Kelpie", "Knarl", "Kraken", "Merpeople", "Manticore", "Niffler", "Nogtail", "Occamy", "Phoenix", "Pixie", "Pogrebin", "Porlock", "Quintaped", "Ramora", "Re'em", "Runespoor", "Salamander", "Sea Serpent", "Snidget", "Sphinx", "Streeler", "Tebo", "Troll", "Unicorn", "Veela", "Werewolf", "Winged Horse", "Yeti", "Zouwu"]

wood = ["Acacia", "Alder", "Apple", "Ash", "Beech", "Blackthorn", "Cedar", "Cherry", "Chestnut", "Ebony",
        "Elder", "Elm", "Fir", "Hawthorn", "Hazel", "Holly", "Hornbeam", "Larch", "Laurel", "Maple", "Oak",
        "Pear", "Pine", "Poplar", "Redwood", "Rowan", "Spruce", "Sycamore", "Vine", "Walnut", "Willow", "Yew"]

core = ["Ashwinder Ash", "Augurey Feather", "Billywig Stinger", "Bicorn Horn", "Boomslang Skin", "Dragon Heartstring", "Phoenix Feather", "Unicorn Hair", "Basilisk Horn", "Kelpie Hair", "Thunderbird Tail Feather", "Veela Hair",
        "Wampus Cat Hair", "Horned Serpent Horn", "Rougarou Hair", "Snallygaster Heartstring", "Jackalope Antler", "Thunderbird Feather", "Rougarou Fang", "White River Monster Spine", "Swamp Mayhaw", "Horned Serpent Horn"]

length = ["9", "9 1/2", "10", "10 1/2", "11", "11 1/2", "12", "12 1/2", "13", "13 1/2", "14"]

terms = [
            "Hogwarts", "Witch", "Wizard", "Durmstrang", "Beauxbatons", "Castle",
            "Dungeon", "Nargle", 'Nargles', "Serpent", "Snake", "Eagle","Lion",
            "Half Blood Prince", "Godric","Salazar","Rowena","Helga",
            "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff",
            "Quidditch", "Golden Snitch", "Snitch", "Quaffle", "Bludger", "Beater", "Seeker", "Chaser", "Keeper",
            "Sorting Hat",
            "Marauder's Map", "Marauders", "Marauder",
            "Triwizard Tournament", "Triwizard Cup",
            "Deathly Hallows", "Deathly Hallow", "Elder Wand", "Resurrection Stone", "Invisibility Cloak",
            "Horcruxes",
            "Patronus",
            "Muggle", "Mudblood",
            "Order Of The Phoenix", "Order Of Phoenix", "Phoenix",
            "Ministry of Magic",
            "Diagon Alley", "Hogsmeade"
            "Platform 9¾", "Hogwarts Express",
            "Forbidden Forest",
            "Chamber of Secrets",
            "Philosopher's Stone",
            "Azkaban",
            "Whomping Willow",
            "Polyjuice Potion", "Draught Of Living Death", "Potion","Felix Felicis","Amortentia","Wolfsbane",
            "Room of Requirement",
            "Parseltongue",
            "Mirror of Erised",
            "Goblet of Fire",
            "House-Elf", "Elf", "House Elf",
            "Thestral",
            "Floo Powder", "Floo",
            "Bezoar",
            "Occlumency", "Legilimency",
            "Gringotts",
            "Quibbler", "Daily Prophet",
            "St. Mungo's",
            "Spell", "Magic", "Ghosts", "Poltergeist",
            "Transfiguration", "Charms", "Defence Against The Dark Arts", "Herbology", "Divination", "Arithmancy", "Potions", "Astronomy", "History of Magic",
            "Spew","Prefect","Time Turner",
            "Wand", "Broom", "Cauldron",
            "Pensieve",
            "Portkey",
            "Howler",
            "Vanishing Cabinet",
            "Wizengamot",
            "Knuts","Sickles","Galleons",
            "Apparition", "Apparate",
            "Curse","Jinx", "Hex",
            "Zonkos", "Three Broomsticks", "Hog's Head", "Ollivanders","Shrieking Shack", "Leaky Cauldron",
            "Newts", "Owls", "Owl", "Newt",
            "Yule Ball",
            "Common Room",
            "Privet Drive", "Grimmauld Place", "Grimmauld",
            "Remembrall", "Sword", "Diadem"
            "Animagus", "Knight Bus"
        ]

characters = [
            "Harry Potter","Harry", "Potter", "Lily","Evans","James","Sirius","Black","Sirius Black","Lupin","Remus","Remus Lupin",
            "Hermione Granger","Hermione", "Granger",
            "Ron Weasley","Ron", "Weasley","Ginny","Fred","George","Percy","Molly","Arthur","Bill","Charlie",
            "Albus Dumbledore","Dumbledore", "Albus","Aberforth",
            "Severus Snape","Severus","Snape",
            "Lord Voldemort","Voldemort","Tom Riddle","Riddle","Tom",
            "Rubeus Hagrid","Hagrid",
            "Draco Malfoy","Malfoy","Draco","Lucius","Narcissa",
            "Neville Longbottom", "Neville","Longbottom","Augusta","Alice","Frank",
            "Luna Lovegood", "Luna", "Lovegood","Xenophilius",
            "Bellatrix Lestrange","Bellatrix","Lestrange","Rodulphus",
            "Nymphadora Tonks","Teddy","Ted","Tonks","Andromeda",
            "Cedric Diggory","Cedric","Diggory","Amos",
            "Dobby","Winky","Kreacher",
            "Cho Chang","Cho",
            "Fleur Delacour","Fleur",
            "Viktor Krum","Krum",
            "Dolores Umbridge","Umbridge","Dolores",
            "Gilderoy Lockhart","Lockhart",
            "Minerva Mcgonagall","Mcgonagall","Minerva",
            "Sybill Trelawney","Trelawney",
            "Filius Flitwick","Flitwick",
            "Pomona Sprout","Sprout",
            "Argus Filch","Filch", "Norris", "Mrs Norris",
            "Poppy Pomfrey","Pomfrey",
            "Cornelius Fudge","Fudge","Cornelius",
            "Barty Crouch","Crouch",
            "Dudley Dursley","Petunia","Vernon ","Dursley",
            "Olympe Maxime", "Madame Maxime", "Maxime",
            "Madam Rosmerta","Rosmerta",
            "Lavender Brown","Lavender",
            "Parvati Patil", "Parvati", "Padma","Padma Patil",
            "Dean Thomas","Dean","Seamus Finnigan","Seamus",
            "Oliver Wood","Wood","Oliver","Marcus Flint","Flint","Katie Bell","Katie","Angelina Johnson","Angelina","Alicia Spinnet","Alicia",
            "Lee Jordan","Lee",
            "Vincent Crabbe","Crabbe","Gregory Goyle","Goyle","Pansy Parkinson","Pansy",
            "Peeves","Nearly Headless Nick","Bloody Baron","Fat Friar","Grey Lady","Moaning Myrtle",
            "Arabella Figg","Mrs Figg","Figg",
            "Igor Karkaroff","Karkaroff", "Igor",
            "Mad-Eye Moody","Moody","Alastor","Alastor Moody",
            "Rita Skeeter","Skeeter",
            "Stan Shunpike", "Ern", "Ernie",
            "Kingsley Shacklebolt","Kingsley",
            "Gellert Grindelwald","Grindelwald",
            "Bathilda Bagshot","Bathilda",
            "Peter Pettigrew","Wormtail","Pettigrew","Peter","Moony","Padfoot","Prongs",
            "Marvolo Gaunt","Merope Gaunt","Morfin Gaunt","Gaunt",
            "Grawp","Firenze","Griphook",
            "Fenrir Greyback","Greyback",
            "Scorpius", "Rose","Hugo",
            "Hedwig", "Scabbers","Crookshanks","Norbert","Trevor","Buckbeak","Nagini","Aragog","Fluffy","Fang",
            "Yaxley", "Zabini", "Blaise", "Blaise Zabini", "Zacharias", "Zacharias Smith",
            "Colin Creevey", "Colin", "Dennis", "Dennis Creevey", "Susan Bones","Susan", "Nott"
        ]

spells = [
    "Accio",
    "Aguamenti",
    "Alohomora",
    "Anapneo",
    "Aparecium",
    "Avada Kedavra",
    "Avis",
    "Colloportus",
    "Crucio",
    "Diffindo",
    "Disillusionment Charm",
    "Dissendium",
    "Engorgio",
    "Episkey",
    "Evanesco",
    "Expecto Patronum",
    "Expelliarmus",
    "Expulso",
    "Ferula",
    "Fidelius Charm",
    "Finestra",
    "Flagrate",
    "Flipendo",
    "Furnunculus",
    "Geminio",
    "Glacius",
    "Homorphus Charm",
    "Immobulus",
    "Impedimenta",
    "Imperio",
    "Impervius",
    "Incarcerous",
    "Incendio",
    "Langlock",
    "Legilimens",
    "Levicorpus",
    "Liberacorpus",
    "Locomotor",
    "Lumos",
    "Lumos Maxima",
    "Lumos Solem",
    "Morsmordre",
    "Muffliato",
    "Nox",
    "Obliviate",
    "Obscuro",
    "Oppugno",
    "Pack",
    "Petrificus Totalus",
    "Point Me",
    "Portus",
    "Prior Incantato",
    "Protego",
    "Protego Horribilis",
    "Protego Totalum",
    "Quietus",
    "Reducto",
    "Relashio",
    "Rennervate",
    "Reparo",
    "Rictusempra",
    "Riddikulus",
    "Scourgify",
    "Sectumsempra",
    "Serpensortia",
    "Silencio",
    "Sonorus",
    "Specialis Revelio",
    "Stupefy",
    "Tarantallegra",
    "Tergeo",
    "Unbreakable Vow",
    "Vulnera Sanentur",
    "Wingardium Leviosa"
]